version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      APP_NAME: gofinabot
      TOKEN: ${TOKEN}
    restart: always
    volumes:
      - ./var:/var/www/gofinabot/db
