version: "3"
services:
  gofinabot:
    container_name: gofinabot
    image: ghcr.io/devil666face/gofinabot:main
    environment:
      APP_NAME: gofinabot
      TOKEN: $TOKEN
      DB_GOFINABOT: $DB_GOFINABOT
    restart: always
    volumes:
      - /opt/docker/gofinabot/db:/gofinabot/db
